# Generated by Django 4.0.4 on 2022-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='A', max_length=150),
            preserve_default=False,
        ),
    ]
