# Generated by Django 4.0.4 on 2022-05-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
