# Generated by Django 4.0.4 on 2022-05-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_reply_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_comment',
            name='active',
        ),
    ]
