# Generated by Django 4.0.4 on 2022-05-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_remove_reply_comment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '01 - Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '02 - Category'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name_plural': '03 - Comment'},
        ),
        migrations.AlterModelOptions(
            name='reply_comment',
            options={'ordering': ('created',), 'verbose_name_plural': '04 - Reply_Comment'},
        ),
    ]
