# Generated by Django 4.0.3 on 2022-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_reservation_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_received',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
