# Generated by Django 4.0.3 on 2022-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_reservation_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_received',
            name='date',
            field=models.CharField(choices=[('S', 'Saturday'), ('SS', 'Sunday')], max_length=50),
        ),
    ]
