# Generated by Django 4.0.3 on 2022-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_alter_reservation_received_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_received',
            name='count',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 Person', '2 Person'), ('3 Person', '3 Person'), ('4 Person', '4 Person'), ('5 Person', '5 Person'), ('6 Person', '6 Person'), ('7 Person', '7 Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='table_number',
            field=models.CharField(choices=[('Table 1', 'Table 1'), ('Table 2', 'Table 2'), ('Table 3', 'Table 3'), ('Table 4', 'Table 4'), ('Table 5', 'Table 5'), ('Table 6', 'Table 6'), ('Table 7', 'Table 7')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation_received',
            name='time',
            field=models.CharField(choices=[('5 - 5.30 PM', '5 - 5.30 PM'), ('5.30 - 6 PM', '5.30 - 6 PM'), ('6 - 6.30 PM', '6 - 6.30 PM'), ('6.30 - 7 PM', '6.30 - 7 PM'), ('7 - 7.30 PM', '7 - 7.30 PM'), ('7.30 - 8 PM', '7.30 - 8 PM'), ('8 - 8.30 PM', '8 - 8.30 PM'), ('8.30 - 9 PM', '8.30 - 9 PM'), ('9 - 9.30 PM', '9 - 9.30 PM'), ('9.30 - 10 PM', '9.30 - 10 PM'), ('10 - 10.30 PM', '10 - 10.30 PM'), ('10.30 - 11 PM', '10.30 - 11 PM'), ('11 - 11.30 PM', '11 - 11.30 PM'), ('11.30 - 11.59 PM', '11.30 - 11.59 PM')], max_length=50),
        ),
    ]
