# Generated by Django 4.0.4 on 2022-05-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_alter_profile_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Bottom',
            new_name='Blog_Bottom',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name_plural': '13 - Audio'},
        ),
        migrations.AlterModelOptions(
            name='blog_bottom',
            options={'verbose_name_plural': '9 - Blog Bottom'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '12 - Contact'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'CONTACT US', 'verbose_name_plural': '11 - Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '10 - Testimonial'},
        ),
    ]
